# Generated by Django 4.2.30 on 2026-05-26 01:45

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programapplication',
            name='national_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, verbose_name='الهوية الوطنية')),
        ),
    ]
