# Generated by Django 4.2.30 on 2026-05-26 01:54

import apps.academic_programs.models
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0002_programapplication_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programapplication',
            name='additional_docs',
            field=models.FileField(blank=True, null=True, upload_to=apps.academic_programs.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'zip', 'doc', 'docx']), apps.core.validators.validate_file_type, apps.core.validators.validate_file_infection], verbose_name='مستندات إضافية'),
        ),
        migrations.AlterField(
            model_name='programapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=apps.academic_programs.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), apps.core.validators.validate_file_type, apps.core.validators.validate_file_infection], verbose_name='السيرة الذاتية'),
        ),
        migrations.AlterField(
            model_name='programapplication',
            name='transcripts',
            field=models.FileField(blank=True, null=True, upload_to=apps.academic_programs.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png']), apps.core.validators.validate_file_type, apps.core.validators.validate_file_infection], verbose_name='كشف الدرجات'),
        ),
    ]
