# Generated by Django 4.2.30 on 2026-05-26 02:26

import apps.academic_programs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0003_alter_programapplication_additional_docs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الوحدة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الوحدة')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='academic_programs.academicprogram', verbose_name='المقرر')),
            ],
            options={
                'verbose_name': 'وحدة دراسية',
                'verbose_name_plural': 'الوحدات الدراسية',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الدرس')),
                ('lesson_type', models.CharField(choices=[('video', 'فيديو'), ('pdf', 'ملف PDF'), ('text', 'مقال / نص'), ('quiz', 'اختبار قصير')], default='video', max_length=20, verbose_name='نوع الدرس')),
                ('content', models.TextField(blank=True, help_text='يستخدم إذا كان الدرس من نوع نص/مقال', verbose_name='محتوى نصي')),
                ('media_file', models.FileField(blank=True, help_text='الفيديو أو ملف الـ PDF', null=True, upload_to=apps.academic_programs.models.lesson_media_path, verbose_name='ملف الدرس')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='المدة التقريبية بالدقائق')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('is_preview', models.BooleanField(default=False, help_text='هل يمكن لغير المشتركين رؤية هذا الدرس؟', verbose_name='معاينة مجانية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academic_programs.programmodule', verbose_name='الوحدة الدراسية')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
