# Generated by Django 4.2.30 on 2026-05-26 15:30

import apps.academic_programs.models
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0004_programmodule_programlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprogram',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='programs/brochures/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'zip']), apps.core.validators.validate_file_type, apps.core.validators.validate_file_infection], verbose_name='البروشور'),
        ),
        migrations.AlterField(
            model_name='academicprogram',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/covers/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), apps.core.validators.validate_file_type, apps.core.validators.validate_file_infection], verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='programlesson',
            name='media_file',
            field=models.FileField(blank=True, help_text='الفيديو أو ملف الـ PDF', null=True, upload_to=apps.academic_programs.models.lesson_media_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'mp4', 'webm', 'mp3']), apps.core.validators.validate_file_type, apps.core.validators.validate_file_infection], verbose_name='ملف الدرس'),
        ),
        migrations.AlterField(
            model_name='programprovider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='providers/logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), apps.core.validators.validate_file_type, apps.core.validators.validate_file_infection], verbose_name='الشعار'),
        ),
    ]
