# Generated by Django 4.2.30 on 2026-06-03 12:09

import apps.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_programs', '0005_alter_academicprogram_brochure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='العنوان بالإنجليزية')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='المعرف')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='specializations/covers/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), apps.core.validators.validate_file_type, apps.core.validators.validate_file_infection], verbose_name='صورة الغلاف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تخصص مهني',
                'verbose_name_plural': 'التخصصات المهنية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecializationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_programs.academicprogram')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_programs.specialization')),
            ],
            options={
                'verbose_name': 'مساق التخصص',
                'verbose_name_plural': 'مساقات التخصص',
                'ordering': ['order'],
                'unique_together': {('specialization', 'course')},
            },
        ),
        migrations.AddField(
            model_name='specialization',
            name='courses',
            field=models.ManyToManyField(related_name='specializations', through='academic_programs.SpecializationCourse', to='academic_programs.academicprogram', verbose_name='المساقات'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='academic_programs.programprovider', verbose_name='المؤسسة المانحة'),
        ),
        migrations.CreateModel(
            name='SpecializationEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'ملتحق'), ('completed', 'مكتمل')], db_index=True, default='enrolled', max_length=20, verbose_name='الحالة')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic_programs.specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'التحاق بمسار',
                'verbose_name_plural': 'التحاقات المسارات',
                'unique_together': {('user', 'specialization')},
            },
        ),
    ]
