# Generated by Django 4.2.30 on 2026-06-23 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_programs', '0006_specialization_specializationcourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAidApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_applying', models.TextField(verbose_name='لماذا تطلب الدعم المالي؟')),
                ('career_goals', models.TextField(verbose_name='كيف سيساعدك هذا البرنامج في تحقيق أهدافك المهنية؟')),
                ('financial_situation', models.TextField(verbose_name='يرجى شرح ظروفك المالية الحالية')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجع')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_aid_applications', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_aid_applications', to='academic_programs.academicprogram')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_financial_aid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب دعم مالي',
                'verbose_name_plural': 'طلبات الدعم المالي',
                'ordering': ['-created_at'],
                'unique_together': {('applicant', 'program')},
            },
        ),
    ]
