# Generated by Django 4.2.30 on 2026-06-23 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_programs', '0007_financialaidapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'فيديو'), ('pdf', 'ملف PDF'), ('text', 'مقال / نص'), ('quiz', 'اختبار قصير'), ('peer_assignment', 'واجب تقييم الزملاء')], default='video', max_length=20, verbose_name='نوع الدرس'),
        ),
        migrations.CreateModel(
            name='PeerAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(verbose_name='نص تسليم الواجب')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_submissions', to='academic_programs.programlesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تسليم واجب زملاء',
                'verbose_name_plural': 'تسليمات واجبات الزملاء',
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='PeerReviewAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='الدرجة من 1 إلى 5')),
                ('feedback', models.TextField(verbose_name='ملاحظات وتغذية راجعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='academic_programs.peerassignmentsubmission')),
            ],
            options={
                'verbose_name': 'تقييم زميل',
                'verbose_name_plural': 'تقييمات الزملاء',
                'unique_together': {('reviewer', 'submission')},
            },
        ),
    ]
