# Generated by Django 4.2.30 on 2026-08-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_programs', '0008_alter_programlesson_lesson_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreferral',
            options={'verbose_name': 'كود إحالة مستخدم', 'verbose_name_plural': 'أكواد إحالات المستخدمين'},
        ),
    ]
