# Generated by Django 4.2.30 on 2026-05-26 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_programs', '0003_alter_programapplication_additional_docs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبت')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='محلول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL, verbose_name='صاحب السؤال')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='academic_programs.academicprogram', verbose_name='المقرر')),
            ],
            options={
                'verbose_name': 'موضوع نقاش',
                'verbose_name_plural': 'مواضيع النقاش',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='الرد')),
                ('is_instructor_reply', models.BooleanField(default=False, verbose_name='رد مدرب')),
                ('is_accepted_answer', models.BooleanField(default=False, verbose_name='إجابة معتمدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_posts', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='course_discussions.discussionthread', verbose_name='الموضوع')),
            ],
            options={
                'verbose_name': 'رد',
                'verbose_name_plural': 'ردود',
                'ordering': ['created_at'],
            },
        ),
    ]
