# Generated by Django 4.2.30 on 2026-08-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_discussions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionpost',
            options={'ordering': ['created_at'], 'verbose_name': 'رد نقاش', 'verbose_name_plural': 'ردود النقاشات'},
        ),
    ]
