version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/learnnov-cloud"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/openedx-platform-master"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    commit-message:
      prefix: "npm-deps"
      include: "scope"
