# Generated by Django 4.2.30 on 2026-05-17 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_uuid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('qr_image', models.ImageField(upload_to='certificates/qr/', verbose_name='QR Code Image')),
                ('verification_url', models.URLField(verbose_name='Verification URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificate QR Code',
                'verbose_name_plural': 'Certificate QR Codes',
            },
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_uuid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('downloadable', 'جاهزة للتحميل'), ('generating', 'قيد الإصدار'), ('error', 'خطأ في الإصدار')], default='downloadable', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generated Certificate',
                'verbose_name_plural': 'Generated Certificates',
            },
        ),
    ]
