# Generated by Django 4.2.30 on 2026-06-03 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_programs', '0006_specialization_specializationcourse_and_more'),
        ('learnnov_certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_uuid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('downloadable', 'جاهزة للتحميل'), ('generating', 'قيد الإصدار'), ('error', 'خطأ في الإصدار')], default='downloadable', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='academic_programs.specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specialization Certificate',
                'verbose_name_plural': 'Specialization Certificates',
            },
        ),
    ]
