# Generated by Django 4.2.30 on 2026-08-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_programs', '0009_alter_userreferral_options'),
        ('learnnov_certificates', '0002_specializationcertificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateqrcode',
            options={'verbose_name': 'رمز QR للشهادة', 'verbose_name_plural': 'رموز QR للشهادات'},
        ),
        migrations.AlterModelOptions(
            name='generatedcertificate',
            options={'verbose_name': 'شهادة مصدرة', 'verbose_name_plural': 'الشهادات المصدرة'},
        ),
        migrations.AlterModelOptions(
            name='specializationcertificate',
            options={'verbose_name': 'شهادة تخصص مهني', 'verbose_name_plural': 'شهادات التخصصات المهنية'},
        ),
        migrations.AlterField(
            model_name='certificateqrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='certificateqrcode',
            name='qr_image',
            field=models.ImageField(upload_to='certificates/qr/', verbose_name='صورة رمز QR'),
        ),
        migrations.AlterField(
            model_name='certificateqrcode',
            name='verification_url',
            field=models.URLField(verbose_name='رابط التحقق'),
        ),
        migrations.AlterField(
            model_name='certificateqrcode',
            name='verify_uuid',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='معرف التحقق'),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='course_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='معرف المساق'),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المساق'),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='grade',
            field=models.CharField(blank=True, max_length=10, verbose_name='الدرجة / التقدير'),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='status',
            field=models.CharField(choices=[('downloadable', 'جاهزة للتحميل'), ('generating', 'قيد الإصدار'), ('error', 'خطأ في الإصدار')], default='downloadable', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='generatedcertificate',
            name='verify_uuid',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='معرف التحقق'),
        ),
        migrations.AlterField(
            model_name='specializationcertificate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار'),
        ),
        migrations.AlterField(
            model_name='specializationcertificate',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='academic_programs.specialization', verbose_name='التخصص المهني'),
        ),
        migrations.AlterField(
            model_name='specializationcertificate',
            name='status',
            field=models.CharField(choices=[('downloadable', 'جاهزة للتحميل'), ('generating', 'قيد الإصدار'), ('error', 'خطأ في الإصدار')], default='downloadable', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='specializationcertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_certificates', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='specializationcertificate',
            name='verify_uuid',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='معرف التحقق'),
        ),
    ]
