# Generated by Django 4.2.30 on 2026-06-03 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learnnov_payments', '0003_order_discount_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('slug', models.SlugField(unique=True, verbose_name='المعرف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('stripe_price_id', models.CharField(blank=True, max_length=200, verbose_name='معرف السعر في Stripe')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('currency', models.CharField(default='SAR', max_length=5, verbose_name='العملة')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'شهري'), ('yearly', 'سنوي')], default='monthly', max_length=20, verbose_name='دورة الفوترة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراكات',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='معرف الاشتراك في Stripe')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('trialing', 'تجريبي'), ('past_due', 'متأخر السداد'), ('canceled', 'ملغي'), ('unpaid', 'غير مدفوع'), ('expired', 'منتهي الصلاحية')], db_index=True, default='expired', max_length=20, verbose_name='الحالة')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='بداية الفترة الحالية')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الفترة الحالية')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='إلغاء عند نهاية الفترة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscriptions', to='learnnov_payments.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اشتراك مستخدم',
                'verbose_name_plural': 'اشتراكات المستخدمين',
            },
        ),
    ]
