# Generated by Django 4.2.30 on 2026-08-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_programs', '0009_alter_userreferral_options'),
        ('learnnov_payments', '0004_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'verbose_name': 'كود خصم', 'verbose_name_plural': 'أكواد الخصم'},
        ),
        migrations.AlterModelOptions(
            name='discountcodeusage',
            options={'verbose_name': 'سجل استخدام كود خصم', 'verbose_name_plural': 'سجلات استخدام أكواد الخصم'},
        ),
        migrations.AlterModelOptions(
            name='hyperpaypayment',
            options={'verbose_name': 'عملية دفع HyperPay', 'verbose_name_plural': 'عمليات دفع HyperPay'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب شراء', 'verbose_name_plural': 'طلبات الشراء'},
        ),
        migrations.AlterModelOptions(
            name='stripepayment',
            options={'verbose_name': 'عملية دفع Stripe', 'verbose_name_plural': 'عمليات دفع Stripe'},
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, help_text='مثال: 100.00 لخصم 100%', max_digits=5, verbose_name='نسبة الخصم %'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=1, verbose_name='أقصى استخدام لكل مستخدم'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='max_uses_total',
            field=models.PositiveIntegerField(default=100, verbose_name='أقصى استخدام إجمالي'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='valid_programs',
            field=models.ManyToManyField(blank=True, to='academic_programs.academicprogram', verbose_name='البرامج المشمولة'),
        ),
        migrations.AlterField(
            model_name='discountcodeusage',
            name='discount_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='learnnov_payments.discountcode', verbose_name='كود الخصم'),
        ),
        migrations.AlterField(
            model_name='discountcodeusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learnnov_payments.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='discountcodeusage',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستخدام'),
        ),
        migrations.AlterField(
            model_name='discountcodeusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='hyperpaypayment',
            name='brand',
            field=models.CharField(blank=True, max_length=20, verbose_name='نوع البطاقة'),
        ),
        migrations.AlterField(
            model_name='hyperpaypayment',
            name='checkout_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='معرف Checkout ID'),
        ),
        migrations.AlterField(
            model_name='hyperpaypayment',
            name='hyperpay_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='حالة HyperPay'),
        ),
        migrations.AlterField(
            model_name='hyperpaypayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hyperpay_payment', to='learnnov_payments.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='hyperpaypayment',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='الرد الأصلي'),
        ),
        migrations.AlterField(
            model_name='hyperpaypayment',
            name='resource_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='مسار المورد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='course_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='معرف المساق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='course_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='اسم المساق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='SAR', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='learnnov_payments.discountcode', verbose_name='كود الخصم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('hyperpay', 'HyperPay')], max_length=20, verbose_name='بوابة الدفع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='academic_programs.academicprogram', verbose_name='البرنامج الأكاديمي'),
        ),
        migrations.AlterField(
            model_name='order',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='كود الإحالة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('failed', 'فشل الدفع'), ('refunded', 'مسترد')], db_index=True, default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='client_secret',
            field=models.CharField(max_length=500, verbose_name='الرمز السري للعميل'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment', to='learnnov_payments.order', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='payment_intent_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='معرف الدفع Intent ID'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='الرد الأصلي'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='حالة Stripe'),
        ),
    ]
