# Generated by Django 4.2.30 on 2026-05-17 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='University Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='University Name (Arabic)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Official Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_marketing', to='academic_programs.programprovider', verbose_name='Academic Provider')),
                ('staff_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university', to=settings.AUTH_USER_MODEL, verbose_name='Staff Account')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='UniversityAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ad Title (English)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='Ad Title (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('image', models.ImageField(upload_to='university_ads/', verbose_name='Ad Image')),
                ('link_url', models.URLField(verbose_name='Destination URL')),
                ('placement', models.CharField(choices=[('dashboard_top', 'Dashboard — Top Banner'), ('dashboard_sidebar', 'Dashboard — Sidebar'), ('search_top', 'Course Search — Top Banner'), ('search_sidebar', 'Course Search — Sidebar'), ('catalog', 'Course Catalog')], default='dashboard_top', max_length=30, verbose_name='Placement')),
                ('priority', models.PositiveSmallIntegerField(default=10, verbose_name='Priority (lower = higher)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('start_date', models.DateTimeField(db_index=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(db_index=True, verbose_name='End Date')),
                ('max_impressions', models.PositiveIntegerField(default=0, verbose_name='Max Impressions (0 = unlimited)')),
                ('impressions_count', models.PositiveIntegerField(default=0, verbose_name='Impressions Count')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Clicks Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='university_ads.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'University Ad',
                'verbose_name_plural': 'University Ads',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('page', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='university_ads.universityad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impression',
                'verbose_name_plural': 'Impressions',
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='university_ads.universityad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Click',
                'verbose_name_plural': 'Clicks',
            },
        ),
        migrations.AddIndex(
            model_name='universityad',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='university__is_acti_de7008_idx'),
        ),
    ]
