# Generated by Django 4.2.30 on 2026-08-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic_programs', '0009_alter_userreferral_options'),
        ('university_ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adclick',
            options={'verbose_name': 'سجل نقرة', 'verbose_name_plural': 'سجلات نقرات الإعلانات'},
        ),
        migrations.AlterModelOptions(
            name='adimpression',
            options={'verbose_name': 'سجل ظهور', 'verbose_name_plural': 'سجلات ظهور الإعلانات'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'جامعة', 'verbose_name_plural': 'الجامعات'},
        ),
        migrations.AlterModelOptions(
            name='universityad',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': 'إعلان جامعي', 'verbose_name_plural': 'إعلانات الجامعات'},
        ),
        migrations.AlterField(
            model_name='adclick',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='university_ads.universityad', verbose_name='الإعلان'),
        ),
        migrations.AlterField(
            model_name='adclick',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='adclick',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='الوقت'),
        ),
        migrations.AlterField(
            model_name='adclick',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='adimpression',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='university_ads.universityad', verbose_name='الإعلان'),
        ),
        migrations.AlterField(
            model_name='adimpression',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AlterField(
            model_name='adimpression',
            name='page',
            field=models.CharField(blank=True, max_length=100, verbose_name='الصفحة'),
        ),
        migrations.AlterField(
            model_name='adimpression',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='الوقت'),
        ),
        migrations.AlterField(
            model_name='adimpression',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='universities/logos/', verbose_name='الشعار'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الجامعة (بالإنجليزية)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الجامعة (بالعربية)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_marketing', to='academic_programs.programprovider', verbose_name='المزود الأكاديمي'),
        ),
        migrations.AlterField(
            model_name='university',
            name='staff_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university', to=settings.AUTH_USER_MODEL, verbose_name='حساب المشرف'),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, verbose_name='الموقع الرسمي'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد النقرات'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف (بالإنجليزية)'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='الوصف (بالعربية)'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='end_date',
            field=models.DateTimeField(db_index=True, verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='image',
            field=models.ImageField(upload_to='university_ads/', verbose_name='صورة الإعلان'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='impressions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد مرات الظهور'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='link_url',
            field=models.URLField(verbose_name='رابط الوجهة'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='max_impressions',
            field=models.PositiveIntegerField(default=0, verbose_name='الحد الأقصى للظهور (0 = غير محدود)'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='placement',
            field=models.CharField(choices=[('dashboard_top', 'لوحة التحكم — الشريط العلوي'), ('dashboard_sidebar', 'لوحة التحكم — الشريط الجانبي'), ('search_top', 'بحث المقررات — الشريط العلوي'), ('search_sidebar', 'بحث المقررات — الشريط الجانبي'), ('catalog', 'دليل المقررات')], default='dashboard_top', max_length=30, verbose_name='موضع الإعلان'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='priority',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='الأولوية (الأقل = أعلى ظهوراً)'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='start_date',
            field=models.DateTimeField(db_index=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الإعلان (بالإنجليزية)'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان الإعلان (بالعربية)'),
        ),
        migrations.AlterField(
            model_name='universityad',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='university_ads.university', verbose_name='الجامعة'),
        ),
    ]
