# Generated by Django 4.2.30 on 2026-05-17 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('placement_type', models.CharField(choices=[('banner_top', 'بانر رأس الصفحة'), ('sidebar', 'الشريط الجانبي'), ('program_card', 'بطاقة البرنامج'), ('search_results', 'نتائج البحث'), ('dashboard', 'لوحة المتعلم')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('base_price_per_day', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
            ],
            options={
                'verbose_name': 'مكان الإعلان',
                'verbose_name_plural': 'أماكن الإعلانات',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('advertiser_name', models.CharField(max_length=200)),
                ('advertiser_email', models.EmailField(max_length=254)),
                ('ad_type', models.CharField(choices=[('image', 'صورة'), ('text', 'نص'), ('video', 'فيديو')], default='image', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/images/')),
                ('headline', models.CharField(blank=True, max_length=100)),
                ('body_text', models.TextField(blank=True)),
                ('call_to_action', models.CharField(default='اعرف أكثر', max_length=50)),
                ('destination_url', models.URLField()),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('active', 'نشط'), ('paused', 'موقوف'), ('expired', 'منتهي'), ('rejected', 'مرفوض')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_impressions', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveSmallIntegerField(default=5)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ads', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='program_ads.adplacement')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['priority', '-is_premium', '-created_at'],
            },
        ),
    ]
