# Generated by Django 4.2.30 on 2026-08-11 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learnnov_exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'خيار إجابة', 'verbose_name_plural': 'خيارات الإجابات'},
        ),
        migrations.AlterModelOptions(
            name='examattempt',
            options={'verbose_name': 'محاولة اختبار', 'verbose_name_plural': 'محاولات الاختبارات'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سؤال', 'verbose_name_plural': 'الأسئلة'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learnnov_exams.question', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnnov_exams.mockexam', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='مكتمل'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='score',
            field=models.FloatField(default=0, verbose_name='الدرجة'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء'),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learnnov_exams.mockexam', verbose_name='الاختبار'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'اختيار من متعدد'), ('tf', 'صح أو خطأ')], default='mcq', max_length=10, verbose_name='نوع السؤال'),
        ),
    ]
